# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75dd3573919b433fd34cc1bde8fbd63bd2c73fb3aca71add087576143e1f2d5d2ab66d5cefff72cdb861803170ad667ebdc128efc74a38a86bad2603e161e3c0

test:
  secret_key_base: 6ba145d0a18cce33038c91d3d8aee487438ed0fa7e36935c1665f3fb1fb75cf1df2a252065944de8e933a83e9053888406f0f3cb4bcfabcee5b205fd7eb4bd34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
